import { lazy } from "react";
import type { RouteMeta } from "./types";

import HomeIcon from "@mui/icons-material/Home";
import CategoryIcon from "@mui/icons-material/Category";
import ArticleIcon from "@mui/icons-material/Article";
import LabelIcon from "@mui/icons-material/Label";

import ROUTES_PATH from "@/core/routes";

export const PATHS: RouteMeta[] = [
  {
    key: "aG9tZSBibG9nIHBlcnNvbgo=",
    path: ROUTES_PATH.home.index,
    pathOriginal: ROUTES_PATH.home.index,
    label: "Trang chủ",
    icon: <HomeIcon />,
    requiresAuth: true,
    roles: [],
    hidden: false,
    component: lazy(() => import("@/modules/home/page")),
  },
  {
    key: "Y2F0ZWdvcnkgYmxvZyBwZXJzb24K",
    path: ROUTES_PATH.category.list,
    pathOriginal: ROUTES_PATH.category.index,
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: false,
    component: lazy(() => import("@/modules/category/pages/category-list")),
  },
  {
    key: "Y2F0ZWdvcnktZGV0YWlsIGJsb2cgcGVyc29uCg==",
    path: ROUTES_PATH.category.detail,
    pathOriginal: ROUTES_PATH.category.index,
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: true,
    component: lazy(() => import("@/modules/category/pages/category-detail")),
  },
  {
    key: "Y2F0ZWdvcnktY29uc3RlYW0gYmxvZyBwZXJzb24K",
    path: ROUTES_PATH.category.update,
    pathOriginal: ROUTES_PATH.category.index,
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/category/pages/update-category")),
  },
  {
    key: "Y2F0ZWdvcnktY29uc3RlYW0gYmxvZyBwZXJzb24K",
    path: ROUTES_PATH.category.create,
    pathOriginal: ROUTES_PATH.category.index,
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/category/pages/create-category")),
  },
  {
    key: "cG9zdCBibG9nZyBwZXJzb24K",
    path: ROUTES_PATH.post.list,
    pathOriginal: ROUTES_PATH.post.index,
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: false,
    component: lazy(() => import("@/modules/post/pages/post-list")),
  },
  {
    key: "cG9zdC1kZXRhaWwgYmxvZyBwZXJzb24K",
    path: ROUTES_PATH.post.detail,
    pathOriginal: ROUTES_PATH.post.index,
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: true,
    component: lazy(() => import("@/modules/post/pages/post-detail")),
  },
  {
    key: "cG9zdC1kZXRhaWwgYmxvZyBwZXJzb24K",
    path: ROUTES_PATH.post.update,
    pathOriginal: ROUTES_PATH.post.index,
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/post/pages/update-post")),
  },
  {
    key: "cG9zdC1kZXRhaWwgYmxvZyBwZXJzb24K",
    path: ROUTES_PATH.post.create,
    pathOriginal: ROUTES_PATH.post.index,
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/post/pages/create-post")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: ROUTES_PATH.tag.list,
    pathOriginal: ROUTES_PATH.tag.index,
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: false,
    component: lazy(() => import("@/modules/tag/pages/tag-list")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: ROUTES_PATH.tag.detail,
    pathOriginal: ROUTES_PATH.tag.index,
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: true,
    component: lazy(() => import("@/modules/tag/pages/tag-detail")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: ROUTES_PATH.tag.update,
    pathOriginal: ROUTES_PATH.tag.index,
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/tag/pages/update-tag")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: ROUTES_PATH.tag.create,
    pathOriginal: ROUTES_PATH.tag.index,
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/tag/pages/create-tag")),
  },
];
