import { lazy } from "react";
import type { RouteMeta } from "./types";

import LoginIcon from "@mui/icons-material/Login";
import HomeIcon from "@mui/icons-material/Home";
import CategoryIcon from "@mui/icons-material/Category";
import ArticleIcon from "@mui/icons-material/Article";
import LabelIcon from "@mui/icons-material/Label";

export const PATHS: RouteMeta[] = [
  {
    key: "bG9naW4gYmxvZyBwZXJzb24K",
    path: "/login",
    pathOriginal: "/login",
    label: "Đăng nhập",
    icon: <LoginIcon />,
    requiresAuth: false,
    roles: [],
    hidden: true,
    component: lazy(() => import("@/modules/auth/pages/login")),
  },
  {
    key: "aG9tZSBibG9nIHBlcnNvbgo=",
    path: "/home",
    pathOriginal: "/home",
    label: "Trang chủ",
    icon: <HomeIcon />,
    requiresAuth: false,
    roles: [],
    hidden: false,
    component: lazy(() => import("@/modules/home/page")),
  },
  {
    key: "Y2F0ZWdvcnkgYmxvZyBwZXJzb24K",
    path: "/categories/list",
    pathOriginal: "/categories/list",
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: false,
    component: lazy(() => import("@/modules/category/pages/category-list")),
  },
  {
    key: "Y2F0ZWdvcnktZGV0YWlsIGJsb2cgcGVyc29uCg==",
    path: "/categories/detail/:id",
    pathOriginal: "/categories",
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: true,
    component: lazy(() => import("@/modules/category/pages/category-detail")),
  },
  {
    key: "Y2F0ZWdvcnktY29uc3RlYW0gYmxvZyBwZXJzb24K",
    path: "/categories/update/:id",
    pathOriginal: "/categories",
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/category/pages/update-category")),
  },
  {
    key: "Y2F0ZWdvcnktY29uc3RlYW0gYmxvZyBwZXJzb24K",
    path: "/categories/create",
    pathOriginal: "/categories",
    label: "Danh mục",
    icon: <CategoryIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/category/pages/create-category")),
  },
  {
    key: "cG9zdCBibG9nZyBwZXJzb24K",
    path: "/posts/list",
    pathOriginal: "/posts/list",
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: false,
    component: lazy(() => import("@/modules/post/pages/post-list")),
  },
  {
    key: "cG9zdC1kZXRhaWwgYmxvZyBwZXJzb24K",
    path: "/posts/detail/:id",
    pathOriginal: "/posts",
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: true,
    component: lazy(() => import("@/modules/post/pages/post-detail")),
  },
  {
    key: "cG9zdC1kZXRhaWwgYmxvZyBwZXJzb24K",
    path: "/posts/update/:id",
    pathOriginal: "/posts",
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/post/pages/update-post")),
  },
  {
    key: "cG9zdC1kZXRhaWwgYmxvZyBwZXJzb24K",
    path: "/posts/create",
    pathOriginal: "/posts",
    label: "Quản lý bài viết",
    icon: <ArticleIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/post/pages/create-post")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: "/tags/list",
    pathOriginal: "/tags",
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: false,
    component: lazy(() => import("@/modules/tag/pages/tag-list")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: "/tags/detail/:id",
    pathOriginal: "/tags",
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN", "USER"],
    hidden: true,
    component: lazy(() => import("@/modules/tag/pages/tag-detail")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: "/tags/update/:id",
    pathOriginal: "/tags",
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/tag/pages/update-tag")),
  },
  {
    key: "dGFnIGJsb2dnIHBlcnNvbgo=",
    path: "/tags/create",
    pathOriginal: "/tags",
    label: "Quản lý tag",
    icon: <LabelIcon />,
    requiresAuth: true,
    roles: ["ADMIN"],
    hidden: true,
    component: lazy(() => import("@/modules/tag/pages/create-tag")),
  },
];
